name: Test

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    - cron: "10 4 * * */2"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4", ruby-head, jruby]
        rubocop_version: [""]
        include:
        - ruby: "2.7"
          rubocop_version: "'1.72.1'"
        - ruby: "3.4"
          rubocop_version: "github: 'rubocop/rubocop'"
    steps:
    - uses: actions/checkout@v5
    - name: Set up RuboCop version overwrite
      if: ${{ matrix.rubocop_version != '' }}
      run: |
        echo "gem 'rubocop', ${{ matrix.rubocop_version }}" > Gemfile.local
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: |
        bundle exec rake test
